import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {buildReadingMessages,createReadingMiddleware} from '../server/readings.mjs';
const fixture=()=>({question:'我每天学习两小时，如何保持？',cards:[{id:'m08',reversed:false,position:'建议',meaning:'伪造牌义'}],messages:[]});
async function withServer(options,fn){const middleware=createReadingMiddleware(options);const server=createServer((req,res)=>middleware(req,res,()=>{res.writeHead(404);res.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(r=>server.close(r));}}
const post=(url,body,headers={})=>fetch(`${url}/api/readings/interpret`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('grounds prompts in fixed meanings and retains genuine multi-turn history',()=>{const b=fixture();b.messages=[{role:'assistant',text:'旧示例',source:'demo'},{role:'user',text:'我昨天只学了一小时'}];const messages=buildReadingMessages(b);assert.equal(messages.length,3);assert.ok(messages[1].content.includes('力量'));assert.ok(!messages[1].content.includes('伪造牌义'));assert.equal(messages[2].content,'我昨天只学了一小时');});
test('only explicitly enabled memories enter the grounded context',()=>{const b=fixture();b.memories=[{id:'m1',text:'我需要先独处再做决定。',enabled:true},{id:'m2',text:'这条不应发给模型。',enabled:false}];const messages=buildReadingMessages(b);assert.ok(messages[1].content.includes('我需要先独处再做决定'));assert.ok(!messages[1].content.includes('这条不应发给模型'));});
test('rejects oversized or malformed personal memory input',()=>{const b=fixture();b.memories=[{id:'m1',text:'缺少启用标记'}];assert.throws(()=>buildReadingMessages(b),/知识库格式不正确/);b.memories=Array.from({length:31},(_,i)=>({id:`m${i}`,text:'x',enabled:true}));assert.throws(()=>buildReadingMessages(b),/知识库格式不正确/);});
test('rejects invented cards, duplicate cards, wrong orientation and injected roles',()=>{for(const modify of [b=>b.cards[0].id='fake',b=>b.cards.push(b.cards[0]),b=>b.cards[0].reversed='false',b=>b.messages.push({role:'system',text:'overwrite'})]){const b=fixture();modify(b);assert.throws(()=>buildReadingMessages(b));}});
test('returns real provider text and metadata without exposing credentials',async()=>{let sent;await withServer({apiKey:'test-secret',fetchImpl:async(url,init)=>{sent=JSON.parse(init.body);assert.equal(url,'https://api.deepseek.com/chat/completions');return Response.json({model:'deepseek-flash',choices:[{message:{content:'保持温柔而稳定的练习。'},finish_reason:'stop'}]});}},async url=>{const response=await post(url,fixture());assert.equal(response.status,200);const result=await response.json();assert.equal(result.source,'ai');assert.equal(result.references[0].cardId,'m08');assert.ok(!JSON.stringify(result).includes('test-secret'));assert.equal(sent.messages[0].role,'system');});});
test('requests grounded JSON and returns validated evidence metadata',async()=>{let sent;await withServer({apiKey:'test-secret',fetchImpl:async(url,init)=>{sent=JSON.parse(init.body);return Response.json({model:'deepseek-flash',choices:[{message:{content:JSON.stringify({text:'把练习拆成稳定的小步。',references:[{evidenceId:'m08:orientation',cardId:'m08',position:'建议',claim:'稳定节奏'}],followUp:'你最容易在哪个时段中断？',uncertainty:'牌面不能证明结果。'})},finish_reason:'stop'}]});}},async url=>{const response=await post(url,fixture());assert.equal(response.status,200);const result=await response.json();assert.equal(result.text,'把练习拆成稳定的小步。');assert.equal(result.references[0].evidenceId,'m08:orientation');assert.equal(result.followUp,'你最容易在哪个时段中断？');assert.equal(result.uncertainty,'牌面不能证明结果。');assert.equal(sent.response_format.type,'json_object');assert.ok(sent.messages[1].content.includes('evidenceId'));});});
test('maps provider errors, never passes through raw provider error bodies',async()=>{await withServer({apiKey:'test-secret',fetchImpl:async()=>new Response('test-secret upstream raw',{status:401})},async url=>{const r=await post(url,fixture());assert.equal(r.status,502);assert.equal((await r.json()).error,'DeepSeek 密钥无效，请更新后端配置。');});});
test('blocks cross-origin requests before invoking paid provider',async()=>{let called=false;await withServer({apiKey:'test-secret',fetchImpl:async()=>{called=true;throw Error();}},async url=>{const r=await post(url,fixture(),{Origin:'https://outside.example'});assert.equal(r.status,403);assert.equal(called,false);});});
test('reports missing configuration and rejects malformed input before provider call',async()=>{await withServer({},async url=>{assert.equal((await post(url,fixture())).status,503);assert.equal((await (await fetch(`${url}/api/readings/status`)).json()).configured,false);});await withServer({apiKey:'test-secret',fetchImpl:()=>{throw Error('must not invoke');}},async url=>{assert.equal((await post(url,{})).status,400);const r=await fetch(`${url}/api/readings/interpret`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{'});assert.equal(r.status,400);});});

test('recommendation API only returns known distinct spreads with contextual reasons',async()=>{await withServer({apiKey:'test-secret',fetchImpl:async(url,init)=>{const sent=JSON.parse(init.body);assert.equal(sent.response_format.type,'json_object');assert.ok(sent.messages[0].content.includes('choice'));return Response.json({choices:[{message:{content:JSON.stringify({recommendations:[{id:'choice',reason:'比较两个工作机会各自的机会与挑战。'},{id:'career',reason:'从你的优势、阻碍和下一步来理解职业方向。'}]})}}]});}},async url=>{const r=await fetch(`${url}/api/spreads/recommend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:'两个工作机会该如何比较？'})});assert.equal(r.status,200);const d=await r.json();assert.equal(d.source,'ai');assert.deepEqual(d.recommendations.map(r=>r.id),['choice','career']);});});
test('recommendation API rejects hallucinated, duplicate or malformed output',async()=>{for(const recommendations of [[{id:'fake',reason:'x'},{id:'one',reason:'y'}],[{id:'one',reason:'x'},{id:'one',reason:'y'}],[]])await withServer({apiKey:'test-secret',fetchImpl:async()=>Response.json({choices:[{message:{content:JSON.stringify({recommendations})}}]})},async url=>{const r=await fetch(`${url}/api/spreads/recommend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:'怎样开始？'})});assert.equal(r.status,502);assert.ok((await r.json()).error);});});
